openapi: 3.0.0
info:
  title: Authorization and Authentication API
  description: Swagger API for Authorization and Authentication API
  version: 1.1.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /auth/register:
    post:
      summary: New user registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  example: craftlinkukraineteam_user
                email:
                  type: string
                  format: email
                  example: nazar@example.com
                password:
                  type: string
                  example: StrongPassword123
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
  /auth/login:
    post:
      summary: User Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: nazar@example.com
                password:
                  type: string
                  example: StrongPassword123
      responses:
        200:
          description: Successful login - returns a JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  /auth/profile:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        200:
          description: User Profile Data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
        401:
          description: Unauthorized access
  /auth/logout:
    post:
      summary: User's Log Out
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        200:
          description: You have successfully logged into the system
  /auth/refresh:
    post:
      summary: Refresh JWT-token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        200:
          description: New JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /auth/forgot-password:
    post:
      summary: You received a password reset link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description:
            Reset link was sent to user's email address
  /auth/reset-password:
    post:
      summary: Reset user's password process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        200:
          description: E-mail verified has been successfully completed!
  /auth/verify-email:
    post:
      tags:
        - Authentication
      summary: Verify User's E-mail Address
      description: Verification of user's email address using verification token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  example: ylYjgUgoTlGHTvJ7LgDgTbE8nGF3GjbRTGM6fg...
      responses:
        200:
          description: E-mail Verified Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: E-mail Verified Successfully!
        400:
          description: Invalid or Expired Token
        404:
          description: User was not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
